name: cleanflutter
description: A new Flutter project with a demo of clean architecture.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

  path_provider: ^1.3.0

  mock_web_server: ^4.1.1

  mockito: "^4.1.1"

  http: ^0.12.0

  injector: ^1.0.8

  clay_containers: ^0.2.2

  device_preview:
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding/
      path: plugins/flutter_plugins/path_provider_fde

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

